import type { ReactNode } from 'react';
import { DOCUMENT_TYPE_LABELS, SOURCE_TYPE_LABELS, VERIFICATION_LABELS } from '../../domain/propertyDataRoom/labels';
import type { ReportSnapshot, VerificationStatus } from '../../domain/propertyDataRoom/types';
import type { ProfessionalReportViewModel, ReportValue } from '../../domain/professionalReport/types';
import { REPORT_VALUE_LABELS } from '../../domain/professionalReport/valuePolicy';
import type { BriefingCategory } from '../../types';
import { isBangbae81511 } from '../../domain/professionalReport/reportAccessPolicy';

const BRIEFING_LABELS: Record<BriefingCategory, string> = { fashion: '패션·라이프스타일', beauty: '뷰티·코스메틱', food: 'F&B·카페', officeCulture: '오피스·문화', transport: '교통', development: '개발', other: '기타' };
const DATA_STATE_LABELS: Partial<Record<ReportValue<unknown>['state'], string>> = { missing: '정보 없음', disconnected: '데이터 미연결', estimated: '추정값', calculated: '계산값', ai_analysis: 'AI 분석', unverified: '확인 필요' };
const formatDate = (value: string) => { const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? value : parsed.toLocaleDateString('ko-KR'); };
const lines = (value: ReportValue<string>) => value.value ? value.value.split(/\r?\n|[•·]/).map((item) => item.trim()).filter(Boolean) : [];

function Value({ label, item, strong = false }: { label: string; item: ReportValue<unknown>; strong?: boolean }) {
  const stateLabel = DATA_STATE_LABELS[item.state];
  return <div className={`pr-value ${strong ? 'strong' : ''}`}><dt>{label}</dt><dd>{item.display}</dd>{stateLabel && <small>{stateLabel}</small>}</div>;
}
function TextPanel({ title, item, emptyText }: { title: string; item: ReportValue<string>; emptyText?: string }) {
  const entries = lines(item);
  return <section className="pr-text-panel"><h3>{title}</h3>{entries.length ? <ul>{entries.map((entry, index) => <li key={`${entry}-${index}`}>{entry}</li>)}</ul> : <p className="pr-empty">{emptyText || item.display}</p>}</section>;
}
function Photo({ item, label, contain = false }: { item: ReportValue<string>; label: string; contain?: boolean }) {
  return <figure className={`pr-photo ${contain ? 'contain' : ''}`}>{item.value ? <img src={item.value} alt={label} /> : <div><span>IMAGE NOT REGISTERED</span><b>{label} 없음</b><small>{item.state === 'disconnected' ? '데이터 미연결' : '등록된 이미지가 없습니다.'}</small></div>}</figure>;
}
function Page({ snapshot, model, page, section, children }: { snapshot: ReportSnapshot; model: ProfessionalReportViewModel; page: number; section: string; children: ReactNode }) {
  return <article className={`professional-report-page page-${page}`}><header className="pr-page-header"><div><strong>PROFESSIONAL PROPERTY REPORT</strong><span>{model.identity.name.display}</span></div><p>{section}</p></header><div className="pr-page-content">{children}</div><footer className="pr-page-footer"><span>{model.identity.companyName.value || '회사 정보 미등록'} · Snapshot 기준 {formatDate(snapshot.generatedAt)}</span><span>v{snapshot.reportVersion} · {page} / 7</span></footer></article>;
}
function SectionTitle({ index, eyebrow, title, copy }: { index: string; eyebrow: string; title: string; copy?: string }) {
  return <div className="pr-section-title"><span>{index}</span><div><small>{eyebrow}</small><h2>{title}</h2>{copy && <p>{copy}</p>}</div></div>;
}
function VerificationSummary({ model }: { model: ProfessionalReportViewModel }) {
  const statuses: VerificationStatus[] = ['verified', 'confirmed', 'imported', 'calculated', 'estimated', 'ai_analysis', 'unverified', 'missing'];
  return <div className="pr-verification-strip">{statuses.filter((status) => model.verification.counts[status] > 0).map((status) => <div key={status}><b>{model.verification.counts[status]}</b><span>{VERIFICATION_LABELS[status]}</span></div>)}</div>;
}

export function ProfessionalReportV1({ snapshot, model, templateId = 'professional-v1' }: { snapshot: ReportSnapshot; model: ProfessionalReportViewModel; templateId?: string }) {
  const briefingItems = model.location.briefingItems.value || [];
  const missingDocuments = model.dataQuality.requiredDocumentsMissing.map((item) => DOCUMENT_TYPE_LABELS[item]);
  const riskLines = lines(model.risks.risks);
  const allowInternalPhotos = model.media.internalPhotoAllowed ?? !isBangbae81511({ address: model.identity.address.value || '', detailAddress: model.identity.detailAddress.value || '' });
  const mainImage = allowInternalPhotos ? model.media.mainImage : { ...model.media.mainImage, value: null, display: '내부사진 비공개', state: 'missing' as const };
  return <div className="professional-report-document" data-template-version={templateId}>
    <Page snapshot={snapshot} model={model} page={1} section="EXECUTIVE PROPERTY OVERVIEW"><div className="pr-cover-title"><p>EXECUTIVE PROPERTY OVERVIEW</p><h1>{model.identity.name.display}</h1><span>{model.identity.address.display}{model.identity.detailAddress.value ? ` ${model.identity.detailAddress.display}` : ''}</span></div><Photo item={mainImage} label={allowInternalPhotos ? '등록된 대표 이미지' : '내부사진 비공개'} /><div className="pr-cover-kpis"><Value label="매매가" item={model.pricing.salePrice} strong /><Value label="토지면적" item={model.land.landAreaPyeong} /><Value label="연면적" item={model.building.totalFloorAreaPyeong} /><Value label="토지 평당가" item={model.pricing.landUnitPrice} /></div><div className="pr-cover-lower"><section><h3>핵심 Property Facts</h3><dl className="pr-facts compact"><Value label="거래유형" item={model.identity.tradeType} /><Value label="용도지역" item={model.land.zoning} /><Value label="주용도" item={model.building.mainUse} /><Value label="명도상태" item={model.pricing.occupancyStatus} /></dl></section><section><h3>위치 요약</h3><p>{model.location.nearbyStation.display} · {model.location.stationDistance.display}</p><p>{model.location.locationAnalysis.display}</p></section></div><div className="pr-cover-verification"><b>{model.dataQuality.reportReady ? 'REPORT DATA READY' : 'ADDITIONAL VERIFICATION REQUIRED'}</b><span>공식 확인 {model.verification.counts.verified}건 · 사용자 확인 {model.verification.counts.confirmed}건 · 확인 필요 {model.verification.counts.unverified + model.verification.counts.missing}건</span></div></Page>
    <Page snapshot={snapshot} model={model} page={2} section="PROPERTY FACTS"><SectionTitle index="02" eyebrow="PROPERTY FACTS" title="토지·건축물 핵심 정보" copy="Snapshot 생성 시점에 저장된 입력값, 계산값 및 확인 상태를 구분해 표시합니다." /><div className="pr-facts-columns"><section><h3>토지 정보</h3><dl className="pr-facts"><Value label="토지면적 (㎡)" item={model.land.landAreaSqm} /><Value label="토지면적 (평)" item={model.land.landAreaPyeong} /><Value label="용도지역" item={model.land.zoning} /><Value label="도로 조건" item={model.land.roadCondition} /></dl></section><section><h3>건축물 정보</h3><dl className="pr-facts"><Value label="건축면적" item={model.building.buildingAreaPyeong} /><Value label="연면적 (㎡)" item={model.building.totalFloorAreaSqm} /><Value label="연면적 (평)" item={model.building.totalFloorAreaPyeong} /><Value label="주용도" item={model.building.mainUse} /><Value label="구조" item={model.building.structure} /><Value label="규모" item={{ ...model.building.groundFloors, display: `지하 ${model.building.basementFloors.display} / 지상 ${model.building.groundFloors.display}` }} /><Value label="준공일" item={model.building.completionDate} /><Value label="건폐율" item={model.building.buildingCoverageRate} /><Value label="용적률" item={model.building.floorAreaRatio} /><Value label="승강기" item={model.building.elevator} /><Value label="주차" item={model.building.parkingSpaces} /></dl></section></div><section className="pr-price-band"><div><small>PRICE</small><strong>{model.pricing.salePrice.display}</strong><span>{REPORT_VALUE_LABELS[model.pricing.salePrice.state]}</span></div><Value label="토지 평당가" item={model.pricing.landUnitPrice} /><Value label="협의 가능" item={model.pricing.negotiable} /><Value label="명도 상태" item={model.pricing.occupancyStatus} /></section><section><h3 className="pr-minor-title">확인 상태</h3><VerificationSummary model={model} /></section></Page>
    <Page snapshot={snapshot} model={model} page={3} section="LOCATION & ACCESSIBILITY"><SectionTitle index="03" eyebrow="LOCATION & ACCESSIBILITY" title="입지와 접근성" copy="외부 실시간 조회 없이 Snapshot에 포함된 지도와 주변 정보만 표시합니다." /><div className="pr-location-grid"><Photo item={model.media.mapImage} label="등록된 위치 지도" contain /><aside><Value label="주소" item={model.identity.address} /><Value label="주요 교통" item={model.location.nearbyStation} /><Value label="도보·접근 거리" item={model.location.stationDistance} /><TextPanel title="입지 특성" item={model.location.locationAnalysis} emptyText="입지 분석 데이터 미연결" /></aside></div><section className="pr-poi"><h3>주변시설 · POI 요약</h3>{briefingItems.length ? <div className="pr-poi-grid">{briefingItems.slice(0, 12).map((item, index) => <article key={`${item.category}-${item.name}-${index}`}><small>{BRIEFING_LABELS[item.category]}</small><b>{item.name}</b><p>{item.description || '설명 정보 없음'}{typeof item.distanceMeters === 'number' ? ` · ${item.distanceMeters}m` : ''}</p></article>)}</div> : <p className="pr-empty large">주변시설 데이터 미연결</p>}</section></Page>
    <Page snapshot={snapshot} model={model} page={4} section="MARKET & PRICE ANALYSIS"><SectionTitle index="04" eyebrow="MARKET & PRICE ANALYSIS" title="시장·가격 분석" copy="확인된 가격과 Snapshot에 저장된 비교 정보만 사용합니다." /><div className="pr-market-hero"><div><small>ASKING PRICE</small><strong>{model.pricing.salePrice.display}</strong><span>{REPORT_VALUE_LABELS[model.pricing.salePrice.state]}</span></div><div><Value label="토지 평당가" item={model.pricing.landUnitPrice} strong /><Value label="토지면적" item={model.land.landAreaPyeong} /><Value label="협의 가능" item={model.pricing.negotiable} /></div></div><section className="pr-comparison"><h3>비교 정보 · 인근 거래사례</h3>{model.investment.nearbyTransactions.value ? <p>{model.investment.nearbyTransactions.display}</p> : <div className="pr-empty large"><b>비교 거래 데이터 미연결</b><span>확인된 거래사례가 Snapshot에 포함되지 않았습니다.</span></div>}</section><div className="pr-two-columns"><TextPanel title="기존 투자분석" item={model.investment.overallOpinion} emptyText="투자분석 데이터 미연결" /><section className="pr-text-panel"><h3>데이터 해석 범위</h3><p>가격 및 계산값은 Snapshot 생성 당시 저장된 자료를 기준으로 합니다. 외부 시세나 실시간 거래 데이터는 포함하지 않습니다.</p><div className="pr-state-key"><span>실제 값</span><span>계산값</span><span>확인 필요</span></div></section></div></Page>
    <Page snapshot={snapshot} model={model} page={5} section="INVESTMENT & DEVELOPMENT"><SectionTitle index="05" eyebrow="INVESTMENT & DEVELOPMENT" title="투자·개발 검토" copy="사용자 입력 또는 기존 분석값이 존재하는 항목만 재현합니다." /><div className="pr-investment-lead"><TextPanel title="핵심 투자 포인트" item={model.investment.investmentPoints} /><TextPanel title="Property 특징" item={model.investment.features} /></div><div className="pr-two-columns tall"><TextPanel title="개발 관련 정보" item={model.investment.developmentPlan} emptyText="개발 관련 정보 없음" /><TextPanel title="활용 가능성 · 추천 용도" item={model.investment.recommendedUse} emptyText="추천 용도 정보 없음" /></div><section className="pr-evidence-note"><b>분석 원칙</b><p>본 페이지는 Snapshot에 저장된 실제 입력·분석 데이터만 표시하며, 근거 없는 투자 의견이나 개발 가능성을 생성하지 않습니다.</p></section></Page>
    <Page snapshot={snapshot} model={model} page={6} section="RISK & VERIFICATION"><SectionTitle index="06" eyebrow="RISK & VERIFICATION" title="리스크와 검증 현황" copy="Data Room의 확인 수준과 추가 확인이 필요한 항목을 한눈에 구분합니다." /><VerificationSummary model={model} /><div className="pr-risk-grid"><section className="pr-risk-main"><h3>주요 리스크</h3>{riskLines.length ? <ol>{riskLines.map((item, index) => <li key={`${item}-${index}`}>{item}</li>)}</ol> : <p className="pr-empty large">등록된 리스크 정보 없음</p>}</section><section><h3>누락 자료</h3>{missingDocuments.length ? <ul>{missingDocuments.map((item) => <li key={item}>{item}</li>)}</ul> : <p className="pr-good">필수 문서 누락 없음</p>}<h3>추가 확인 필요</h3><p>미확인 {model.verification.counts.unverified}건 · 데이터 없음 {model.dataQuality.counts.missing}개 · 미연결 {model.dataQuality.counts.disconnected}개</p></section></div><section className="pr-check-list"><h3>검증 기록</h3>{model.verification.items.length ? model.verification.items.slice(0, 10).map((item, index) => <div key={`${item.fieldKey}-${index}`}><span>{index + 1}</span><b>{VERIFICATION_LABELS[item.status]}</b><p>{item.note || '별도 확인 메모 없음'}</p><small>{item.verifiedAt ? formatDate(item.verifiedAt) : '확인일 미기록'}</small></div>) : <p className="pr-empty large">등록된 검증 기록 없음</p>}</section></Page>
    <Page snapshot={snapshot} model={model} page={7} section="DATA ROOM SUMMARY"><SectionTitle index="07" eyebrow="DATA ROOM SUMMARY" title="자료실과 생성 이력" copy="보고서와 함께 저장된 Data Room 요약 및 출처 이력입니다." /><div className="pr-data-room-kpis"><div><b>{model.documents.count}</b><span>문서</span><small>공식 확인 {model.documents.verifiedCount}</small></div><div><b>{model.media.items.length}</b><span>사진·미디어</span><small>Snapshot 연결 기준</small></div><div><b>{model.sources.count}</b><span>데이터 출처</span><small>출처 기록 기준</small></div><div><b>{model.digitalTwin.connected ? model.digitalTwin.count : '—'}</b><span>Digital Twin</span><small>{model.digitalTwin.connected ? `처리 완료 ${model.digitalTwin.readyCount}` : '데이터 미연결'}</small></div></div><div className="pr-data-room-columns"><section><h3>문서 목록</h3>{model.documents.items.length ? model.documents.items.slice(0, 9).map((item) => <div className="pr-record" key={item.id}><b>{item.title}</b><span>{DOCUMENT_TYPE_LABELS[item.documentType]} · {VERIFICATION_LABELS[item.verificationStatus]}</span></div>) : <p className="pr-empty large">연결된 문서 없음</p>}</section><section><h3>데이터 출처</h3>{model.sources.items.length ? model.sources.items.slice(0, 9).map((item) => <div className="pr-record" key={item.id}><b>{item.sourceName}</b><span>{SOURCE_TYPE_LABELS[item.sourceType]} · {VERIFICATION_LABELS[item.verificationStatus]}</span></div>) : <p className="pr-empty large">데이터 출처 미연결</p>}</section></div><section className="pr-generation-meta"><div><small>GENERATED</small><b>{formatDate(snapshot.generatedAt)}</b></div><div><small>REPORT VERSION</small><b>v{snapshot.reportVersion}</b></div><div><small>TEMPLATE</small><b>{snapshot.templateVersion}</b></div><div><small>ENGINE</small><b>{snapshot.engineVersion || model.generated.engineVersion || '미기록'}</b></div><div><small>STATUS</small><b>{snapshot.status.toUpperCase()}</b></div></section><section className="pr-final-note"><b>Snapshot 불변성</b><p>본 보고서는 생성 시점의 snapshotData만으로 재현되며, 이후 Property 변경은 이 보고서의 내용에 영향을 주지 않습니다.</p><small>Snapshot ID · {snapshot.id}</small></section></Page>
  </div>;
}
