import { ApartmentRounded, AutoAwesomeRounded, DescriptionOutlined, FactCheckRounded, GavelRounded, HistoryRounded, HomeWorkRounded, HubRounded, MapOutlined, PaidRounded, PictureAsPdfOutlined, SettingsRounded, ShareRounded, ThreeDRotationRounded, UploadFileRounded, ViewInArRounded } from '@mui/icons-material';
import { Button } from '@mui/material';
import { NavLink, Outlet, useLocation, useNavigate } from 'react-router-dom';

export default function Layout() {
  const location = useLocation(); const navigate = useNavigate();
  const editMatch = location.pathname.match(/^\/property\/([^/]+)\/edit$/); const propertyId = editMatch?.[1];
  return <div className="app-shell"><aside><div className="brand"><span>DA</span><div>DA:ON ASSET<small>PROPERTY DATA & AGENT PLATFORM</small></div></div><nav><NavLink to="/control-center"><HubRounded />A0 Control Center</NavLink><NavLink to="/" end><ApartmentRounded />물건 / Data Room</NavLink><NavLink to="/bulk-intake"><FactCheckRounded />A1–A3 Intake · Verification</NavLink><NavLink to="/interior"><HomeWorkRounded />A4–A5 Interior Workspace</NavLink><NavLink to="/spatial"><ViewInArRounded />A6 Spatial Workspace</NavLink><NavLink to="/digital-twin-intake"><UploadFileRounded />3D · 도면 자료 등록</NavLink><NavLink to="/digital-twin"><ThreeDRotationRounded />A6–A7 Digital Twin</NavLink><NavLink to="/income"><PaidRounded />임대 · 수익 분석</NavLink><NavLink to="/external-shares"><ShareRounded />외부 공유 센터</NavLink><NavLink to="/room-ops"><HubRounded />A5/A8/A10 Room Ops</NavLink><NavLink to="/risk"><GavelRounded />A9 Risk / Compliance</NavLink><NavLink to="/agents"><AutoAwesomeRounded />Agent Operations</NavLink><NavLink to="/report-history"><HistoryRounded />보고서 버전 이력</NavLink><NavLink to="/import"><UploadFileRounded />엑셀 대량 등록</NavLink><NavLink to="/settings"><SettingsRounded />회사 설정</NavLink></nav><div className="side-note">AGENT MODULAR ARCHITECTURE<small>A0 Integrator → A1~A10 isolated agents → A11 Report deferred</small></div></aside><main>{propertyId && <div className="detail-document-actions"><span>MASTER 문서</span><Button size="small" startIcon={<DescriptionOutlined />} onClick={() => navigate(`/document/report/${propertyId}`)}>7P 상세보고서</Button><Button size="small" startIcon={<PictureAsPdfOutlined />} onClick={() => navigate(`/document/proposal/${propertyId}`)}>1P 요약제안서</Button><Button size="small" startIcon={<MapOutlined />} onClick={() => navigate(`/properties/${propertyId}/briefing`)}>입지 브리핑</Button></div>}<Outlet /></main></div>;
}
